### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by hakanak** [VuWall/GmailSignatureSync#1]
Hi, Application error:

Help me :)

`An unhandled exception of type 'System.NullReferenceException' occurred in GmailSignatureSync.exe`

Error image : http://sakaryauniversitesi.com/123123123123.PNG

**Comment by MattAlex151** [comment]
Hey, I'm happy to help you but I'm in Africa until Jan 4 without a
computer/reliable internet access. Sorry! I'll get it on ASAP when I'm
home.

**Comment by hakanak** [comment]
i wait your answer.
Thanks

**Comment by MattAlex151** [comment]
Hey, so I see from your picture you commented out the line that requests the access token, why is this? 

`if (!credential.RequestAccessTokenAsync(System.Threading.CancellationToken.None).Result)`
  `  throw new InvalidOperationException("Access token failed.");`

Also worth checking is that your Service Account Email is correct, and the password for your Key.p12 is also correct. Let me know!
